### ISSUE TITLE
eHMP Architecture

### ISSUE THREAD

**Issue by utishrajk** [OSEHRA-Sandbox/eHMP#1]
Is it possible to replace your data layer and Cache database with something else (particularly FHIR storage with JSON noSQL database)?

Are your RPC calls and polling mechanism for integration with VistA usable for sourcing data from other EHR systems?

Thanks,
UR

**Comment by petercyli** [comment]
Yes to your first question.  I believe KRM's [LEAF](https://www.krminc.com/custom-it-solutions/leaf/) framework has the same approach, but it is not a FHIR storage.

As to the RPC calls and the mechanism for VistA Integration, I don't think it is not usable for sourcing data from other EHR systems; they are customized for accessing VistA.  

However, there are connectors created to access other sources such as the DoD's ALHTA EHR. 

Will you be interested in open source development to create the FHIR storage, making eHMP RDK a FHIR endpoint? Or develop connectors that interfaces with EHR with FHIR interface?  OSEHRA is looking for interested partners to continue the eHMP development.

Peter
